#!/usr/bin/env ruby

# usage is 
# fetch_mysql [environment]

# This script will connect to the remote server, dump its database, zip it, 
# and copy it locally into ./script/db/
# This allows you to quickly get a similar db to that of the server

require "yaml"


host="crumbtrail.net"

# If no env provided, assume production since we're copying from the server

env = ARGV[0]
if (env =~ /production|development|testing/).nil?
  env = "production"
  i = 0
else
  i = 1
end
tables = ARGV[i, ARGV.length].join(' ')
puts "using environment '#{env}'"
puts "fetching tables '#{tables}'"

# Parse credentials from env file
f=YAML::load(File.open('config/database.yml'))

v=f[env]

db = v["database"]
user = v["username"]
pass = v["password"]

filename = "#{db}#{("-"+tables.delete(' ')) unless tables.nil?}"

puts "downloading to file '#{filename}'"

# build a string that tells mysql to compres a table
compress="mkdir dbdump 2> /dev/null; " +
  "mysqldump -u#{user} -p#{pass} #{db} #{tables} | gzip -cf > dbdump/#{filename}.gz"


puts "compressing database file on server"
# execute the command remotely
puts `ssh #{user}@#{host} "#{compress}"`

puts "downloading db file from server"
`mkdir ./script/db 2> /dev/null`
puts `scp #{user}@#{host}:~/dbdump/#{filename}.gz ./script/db/`
`gunzip -f ./script/db/#{filename}.gz`
